// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rickdane.springmodularizedproject.domain;

import com.rickdane.springmodularizedproject.domain.UserRoleDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserRoleDataOnDemand_Roo_Configurable {
    
    declare @type: UserRoleDataOnDemand: @Configurable;
    
}
