// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rickdane.springmodularizedproject.module.consumabledata.domain;

import com.rickdane.springmodularizedproject.module.consumabledata.domain.Website;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Website_Roo_Configurable {
    
    declare @type: Website: @Configurable;
    
}
